// Generates themes/*.json and the icons/ file icon theme from the shared design in src/ and the
// two palettes.
//
//   node scripts/build.mjs              write both themes and both icon sets
//   node scripts/build.mjs --check      fail if themes/ or icons/ is stale (for CI)
//   node scripts/build.mjs --coverage   also list registered VS Code colours no theme sets
//
// The shared maps (src/workbench.json, src/syntax.json) name palette roles only. Every rule that
// keeps Dark and Light one design lives here, and a violation fails the build rather than warning:
//   - both palettes define exactly the same roles
//   - every role a map names exists, and every role a palette defines is used somewhere
//   - no raw colour appears in a shared map or an icon template
//   - every icon the icon map names has a template, and every template is used
//   - every workbench key is registered by VS Code (scripts/vscode-color-ids.json)

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = new Set(process.argv.slice(2));
const readJson = (rel) => JSON.parse(readFileSync(join(root, rel), 'utf8'));

const BASES = [
  { palette: 'src/palettes/dark.json', out: 'themes/fili-vscode2026-dark-color-theme.json' },
  { palette: 'src/palettes/light.json', out: 'themes/fili-vscode2026-light-color-theme.json' },
];
// Variant palettes (generated by scripts/variants.mjs) hold only the roles Visual Studio changes;
// each is merged onto its base, so a variant can never add a role or drop one.
const VARIANT_DIR = 'src/palettes/variants';
const VARIANTS = existsSync(join(root, VARIANT_DIR))
  ? readdirSync(join(root, VARIANT_DIR)).filter((f) => f.endsWith('.json')).sort()
    .map((f) => ({ palette: `${VARIANT_DIR}/${f}`, out: `themes/fili-vscode2026-${f.slice(0, -5)}-color-theme.json` }))
  : [];
const HEX = /^#[0-9A-F]{6}([0-9A-F]{2})?$/i;
const REF = /^([A-Za-z][A-Za-z0-9]*)(?:\/(\d{1,3}))?$/;

const errors = [];
const fail = (msg) => errors.push(msg);

const workbench = withoutComment(readJson('src/workbench.json'));
const syntax = readJson('src/syntax.json');
const { vscodeVersion, colors: registry } = readJson('scripts/vscode-color-ids.json');
const bases = BASES.map((t) => ({ ...t, ...readJson(t.palette) }));

// --- parity -------------------------------------------------------------------------------------
const [first, ...rest] = bases;
const firstRoles = Object.keys(first.roles);
for (const p of rest) {
  const roles = Object.keys(p.roles);
  for (const r of firstRoles) if (!(r in p.roles)) fail(`${p.palette}: missing role '${r}' (defined in ${first.palette})`);
  for (const r of roles) if (!(r in first.roles)) fail(`${first.palette}: missing role '${r}' (defined in ${p.palette})`);
}
const variants = VARIANTS.map((t) => {
  const v = readJson(t.palette);
  const base = bases.find((b) => b.type === v.base);
  if (!base) { fail(`${t.palette}: base '${v.base}' is not a base palette`); return null; }
  for (const r of Object.keys(v.roles)) if (!(r in base.roles)) fail(`${t.palette}: overrides '${r}', which ${base.palette} does not define`);
  return { ...t, name: v.name, type: base.type, vs: v.vs, roles: { ...base.roles, ...v.roles } };
}).filter(Boolean);
const palettes = [...bases, ...variants];
for (const p of palettes) {
  for (const [role, entry] of Object.entries(p.roles)) {
    if (!Array.isArray(entry) || !HEX.test(entry[0]) || typeof entry[1] !== 'string' || !entry[1]) {
      fail(`${p.palette}: role '${role}' must be ["#RRGGBB[AA]", "provenance"]`);
    }
  }
}

// --- resolution ---------------------------------------------------------------------------------
const used = new Set();

function resolve(ref, palette, where) {
  if (ref === 'transparent') return '#00000000';
  if (typeof ref !== 'string' || ref.startsWith('#')) {
    fail(`${where}: '${ref}' is a raw colour; shared maps may only name palette roles`);
    return undefined;
  }
  const m = REF.exec(ref);
  if (!m) { fail(`${where}: '${ref}' is not 'role' or 'role/NN'`); return undefined; }
  const [, role, pct] = m;
  used.add(role);
  const entry = palette.roles[role];
  if (!entry) { fail(`${where}: unknown role '${role}'`); return undefined; }
  const hex = entry[0].toUpperCase();
  if (pct === undefined) return hex;
  const n = Number(pct);
  if (n < 0 || n > 100) { fail(`${where}: opacity ${n}% out of range`); return undefined; }
  const baseAlpha = hex.length === 9 ? parseInt(hex.slice(7), 16) / 255 : 1;
  const alpha = Math.round(baseAlpha * (n / 100) * 255);
  return hex.slice(0, 7) + alpha.toString(16).padStart(2, '0').toUpperCase();
}

function buildTheme(p) {
  const colors = {};
  for (const [key, ref] of Object.entries(workbench)) {
    if (!(key in registry)) fail(`src/workbench.json: '${key}' is not a colour VS Code registers`);
    const v = resolve(ref, p, `src/workbench.json '${key}'`);
    if (v) colors[key] = v;
  }

  const tokenColors = syntax.tokenColors.map((rule, i) => {
    const where = `src/syntax.json tokenColors[${i}] (${rule.name})`;
    const settings = {};
    if (rule.role) settings.foreground = resolve(rule.role, p, where);
    if (rule.fontStyle !== undefined) settings.fontStyle = rule.fontStyle;
    if (!rule.scope?.length) fail(`${where}: no scope`);
    return { name: rule.name, scope: rule.scope, settings };
  });

  const semanticTokenColors = {};
  for (const [selector, value] of Object.entries(syntax.semanticTokenColors)) {
    const where = `src/syntax.json semanticTokenColors '${selector}'`;
    if (typeof value === 'string') {
      semanticTokenColors[selector] = resolve(value, p, where);
    } else {
      const { role, ...style } = value;
      semanticTokenColors[selector] = { foreground: resolve(role, p, where), ...style };
    }
  }

  return {
    $schema: 'vscode://schemas/color-theme',
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors,
    tokenColors,
    semanticTokenColors,
  };
}

const built = palettes.map((p) => ({ p, theme: buildTheme(p) }));

// --- file icon theme ----------------------------------------------------------------------------
// src/icons/*.svg are templates whose colours are {{role}} placeholders; each is rendered once per
// base palette. Dark's set is the icon theme's default and Light's its 'light' variant; the tinted
// variants share their base's icons, since VS Code has one icon theme per light/dark kind.
const iconMap = withoutComment(readJson('src/icon-theme.json'));
const templates = Object.fromEntries(readdirSync(join(root, 'src/icons'))
  .filter((f) => f.endsWith('.svg'))
  .map((f) => [f.slice(0, -4), readFileSync(join(root, 'src/icons', f), 'utf8')]));
const referenced = new Set();
const ref = (name, where) => {
  if (!(name in templates)) fail(`src/icon-theme.json ${where}: no template src/icons/${name}.svg`);
  referenced.add(name);
  return name;
};
for (const [k, v] of Object.entries(iconMap)) {
  if (typeof v === 'string') ref(v, `'${k}'`);
  else for (const [kk, vv] of Object.entries(v)) ref(vv, `${k} '${kk}'`);
}
for (const name of Object.keys(templates)) if (!referenced.has(name)) fail(`src/icons/${name}.svg is not used by src/icon-theme.json`);

const outputs = built.map(({ p, theme }) => ({ path: p.out, text: JSON.stringify(theme, null, 2) + '\n' }));
for (const p of bases) {
  for (const [name, svg] of Object.entries(templates)) {
    if (/#[0-9a-f]{3,8}\b/i.test(svg)) fail(`src/icons/${name}.svg contains a raw colour; use {{role}}`);
    const text = svg.replace(/\{\{(\w+)\}\}/g, (_, role) => resolve(role, p, `src/icons/${name}.svg`) ?? '');
    outputs.push({ path: `icons/${p.type}/${name}.svg`, text });
  }
}
const suffix = (type) => (type === first.type ? '' : `_${type}`);
const remap = (type) => Object.fromEntries(Object.entries(iconMap).map(([k, v]) => [k,
  typeof v === 'string' ? v + suffix(type) : Object.fromEntries(Object.entries(v).map(([kk, vv]) => [kk, vv + suffix(type)]))]));
const iconDefinitions = {};
for (const p of bases) {
  for (const name of Object.keys(templates)) iconDefinitions[name + suffix(p.type)] = { iconPath: `./${p.type}/${name}.svg` };
}
const iconTheme = { iconDefinitions, ...remap(first.type), hidesExplorerArrows: false };
for (const p of rest) iconTheme[p.type] = remap(p.type);
outputs.push({ path: 'icons/fili-vscode2026-icon-theme.json', text: JSON.stringify(iconTheme, null, 2) + '\n' });

for (const r of firstRoles) if (!used.has(r)) fail(`role '${r}' is defined in both palettes but nothing uses it`);

// package.json must contribute exactly the themes generated here, in this order, with the right kind.
const expected = palettes.map((p) => ({ label: p.name, uiTheme: p.type === 'dark' ? 'vs-dark' : 'vs', path: `./${p.out}` }));
const contributed = readJson('package.json').contributes?.themes ?? [];
if (JSON.stringify(contributed) !== JSON.stringify(expected)) {
  fail(`package.json contributes.themes does not match the generated themes; it should be:\n${JSON.stringify(expected, null, 2)}`);
}

if (errors.length) {
  console.error(`build failed with ${errors.length} error(s):`);
  for (const e of [...new Set(errors)]) console.error(`  - ${e}`);
  process.exit(1);
}

// --- output -------------------------------------------------------------------------------------
let stale = false;
let unchanged = 0;
for (const { path, text } of outputs) {
  const target = join(root, path);
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (args.has('--check')) {
    if (current !== text) { stale = true; console.error(`stale: ${path} (run npm run build)`); }
  } else if (current !== text) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, text);
    console.log(`wrote ${path}`);
  } else {
    unchanged++;
  }
}
// Generated icon files that no template produces any more are leftovers: delete them (or, under
// --check, report them) so a removed template cannot linger in the package.
const produced = new Set(outputs.map((o) => o.path));
for (const p of bases) {
  const dir = join(root, 'icons', p.type);
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir)) {
    const rel = `icons/${p.type}/${f}`;
    if (produced.has(rel)) continue;
    if (args.has('--check')) { stale = true; console.error(`stale: ${rel} is no longer generated (run npm run build)`); }
    else { rmSync(join(dir, f)); console.log(`removed ${rel}`); }
  }
}
for (const f of readdirSync(join(root, 'themes'))) {
  const rel = `themes/${f}`;
  if (produced.has(rel)) continue;
  if (args.has('--check')) { stale = true; console.error(`stale: ${rel} is no longer generated (run npm run build)`); }
  else { rmSync(join(root, rel)); console.log(`removed ${rel}`); }
}
if (unchanged) console.log(`${unchanged} generated file(s) unchanged`);
if (stale) process.exit(1);

const keys = Object.keys(workbench);
console.log(`${firstRoles.length} roles per palette, ${keys.length} workbench colours, ` +
  `${syntax.tokenColors.length} token rules, ${Object.keys(syntax.semanticTokenColors).length} semantic selectors`);
console.log(`${palettes.length} themes: ${bases.length} bases and ${variants.length} variants.`);
console.log(`VS Code ${vscodeVersion} registers ${Object.keys(registry).length} colours; every theme sets ${keys.length}.`);

if (args.has('--coverage')) {
  const unset = Object.keys(registry).filter((k) => !(k in workbench));
  console.log(`\nnot set (${unset.length}) — VS Code derives these from other keys or uses its own default:`);
  for (const k of unset) console.log(`  ${k}`);
}

// --- contrast: the same pairs, side by side, so a drift between the two modes shows up ---------
const PAIRS = [
  ['fg', 'card', 4.5], ['fg', 'chrome', 4.5], ['fgSecondary', 'card', 4.5], ['fgTertiary', 'card', 3],
  ['tabTextInactive', 'tabWell', 3], ['statusBarText', 'statusBar', 4.5], ['accentFg', 'accent', 4.5], ['accentStrongFg', 'accentStrong', 4.5],
  ['synText', 'editor', 7], ['lineNumber', 'editor', 3],
  ['synKeyword', 'editor', 4.5], ['synControl', 'editor', 4.5], ['synString', 'editor', 4.5],
  ['synComment', 'editor', 4.5], ['synNumber', 'editor', 4.5], ['synType', 'editor', 3],
  ['synInterface', 'editor', 3], ['synMethod', 'editor', 4.5], ['synVariable', 'editor', 4.5],
  ['synPreprocessor', 'editor', 3], ['synDocText', 'editor', 3], ['link', 'card', 4.5],
  ['error', 'card', 3], ['warning', 'card', 3], ['info', 'card', 3], ['success', 'card', 3],
  ['gitAdded', 'card', 3], ['gitModified', 'card', 3], ['gitDeleted', 'card', 3],
];
const lum = (hex) => {
  const c = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((m, n) => n - m); return (x + 0.05) / (y + 0.05); };
console.log(`\ncontrast (WCAG)                ${bases.map((p) => p.type.padEnd(10)).join('')} min`);
for (const [fgRole, bgRole, min] of PAIRS) {
  const cells = bases.map((p) => {
    const r = ratio(p.roles[fgRole][0], p.roles[bgRole][0]);
    return `${r.toFixed(2)}${r < min ? '!' : ' '}`.padEnd(10);
  });
  console.log(`  ${`${fgRole} / ${bgRole}`.padEnd(28)} ${cells.join('')} ${min}`);
}
const low = [];
for (const v of variants) {
  for (const [fgRole, bgRole, min] of PAIRS) {
    const r = ratio(v.roles[fgRole][0], v.roles[bgRole][0]);
    if (r < min) low.push(`  ${v.name.padEnd(36)} ${`${fgRole} / ${bgRole}`.padEnd(28)} ${r.toFixed(2)} (min ${min})`);
  }
}
console.log(low.length ? `\nvariant pairs below the minimum (${low.length}):\n${low.join('\n')}` : `\nall ${variants.length} variants meet every contrast minimum`);

function withoutComment(o) {
  const { $comment, ...rest } = o;
  return rest;
}
